# Generated by Django 4.1.2 on 2022-12-30 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_remove_user_date_joined_remove_user_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('img', models.ImageField(upload_to='clubs')),
                ('events', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='management.event')),
            ],
        ),
    ]
