# Generated by Django 4.1.2 on 2022-12-30 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_alter_event_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='short_desc',
            field=models.TextField(),
        ),
    ]
