# Generated by Django 4.1.2 on 2022-12-30 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_alter_event_short_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leader', to='management.user'),
        ),
    ]
