# Generated by Django 4.1.2 on 2022-12-30 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_club_leader'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.CharField(default='', max_length=200),
        ),
    ]
