# Generated by Django 4.1.2 on 2022-12-30 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_event_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='slug',
            field=models.SlugField(blank=True, default='', unique=True),
        ),
        migrations.AddField(
            model_name='club',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='clubs', to='management.user'),
        ),
        migrations.AlterField(
            model_name='event',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='events', to='management.user'),
        ),
    ]
